# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer # Adjust Xcode version as needed

    - name: Build and run tests
      run: xcodebuild test -workspace DependencyInjectionVsDependencyInversion.xcodeproj -scheme DependencyInjectionVsDependencyInversion -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0'
