name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3

    - name: Xcode Setup
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2'

    - name: Run tests
      run: |
        cd GitHubActions
        xcodebuild test -project DependencyInjectionVsDependencyInversion.xcodeproj -scheme DependencyInjectionVsDependencyInversion clean build -sdk iphoneos -destination "platform=iOS Simulator,OS=16.1,name=iPhone 14 Pro Max" CODE_SIGNING_ALLOWED=No
